### ISSUE TITLE
(f)(data)sync, syncfs, msync default annotations

### ISSUE THREAD

**Issue by HassineRhouma-Myposter** [amytai/cinterrupts-osdi#2]
Hello!

I'm playing around with the default cint annotations of some of the syscalls that were mentioned in the paper for a university project.

I'm wondering where the default annotations for (f)(data)sync, syncfs and msync were set. I sadly can't find anything in any of the kernel patches in the repo. Were the annotations for these syscalls maybe retracted for some reason?

I would appreciate any sort of answer/feedback!

Thanks in advance.

**Comment by amytai** [comment]
Thanks for your interest!

Default annotations for these syscalls weren't included in our kernel patches. However, you can look at how annotations were [added](https://github.com/amytai/cinterrupts-osdi/blob/d4dfa8af67808886f61d89f261a4a6237162a031/linux-kernel/cinterrupts-02-rocks-addon.patch#L928) to the read/write syscalls, and port that to the sync family of syscalls.

**Comment by HassineRhouma-Myposter** [comment]
Alright. Thank you!
